### ISSUE TITLE
Merging our fork to upstream

### ISSUE THREAD

**Issue by augustocdias** [carl-wallace/rust-pki#61]
Hello,

Our company forked your repo to work with certval and since then we've made many commits on the [fork](https://github.com/carl-wallace/rust-pki/compare/main...wireapp:rust-pki:wire/stable). We would like to merge our changes to upstream, use the main repo and archive ours.

What would be the best approach to do so? We have 25 commits with some fixes, tests and some features that we needed.

**Comment by carl-wallace** [comment]
Excellent. This is good timing as I was planning to look at doing a proper release once the next round of releases were done for the [formats](https://github.com/rustcrypto/formats) crates and that work is very active now and nearing conclusion. I will be traveling all day today, let me get back to you re: next steps, but the cert_limbo branch is the target for progressing so aligning with it is a good step.

**Comment by carl-wallace** [comment]
I'm still working through your commits. In the meantime, here's a [diff](https://github.com/wireapp/rust-pki/compare/wire/stable...carl-wallace:rust-pki:cert_limbo) of changes on the cert_limbo branch relative to your stable branch. Do you have any concerns about any of these changes? Re: what I've reviewed so far, I think I'd like to retain Cargo.lock. Else, looks great so far. Thanks for the work.

**Comment by augustocdias** [comment]
I'll go through the diff this week and get back to you if I find something that wouldn't work for us. The biggest and probably only restriction we have, is that it must compile/run in web assembly. Other than that, we can adjust our code for API changes without any problem. I can't think of anything else that would be a blocker for us at this moment.

**Comment by carl-wallace** [comment]
I completed a pass over all the commits. The deletion of Cargo.lock is the only thing that caught my eye as something I'd not want to do. If you want to prepare a PR as you review the diff (which is largely tightening things up with new types), I'll test it all out in context and plan to merge into cert_limbo. Merging into main and releasing to crates would follow after the next set of formats releases are completed.

**Comment by augustocdias** [comment]
Awesome. Do you prefer to have all of the commits squashed for the PR or as it is? The cargo.lock is not an issue for us. I'll have time to rebase and prepare a PR next week.

**Comment by carl-wallace** [comment]
As-is is fine. No need to rush to get PR for next week. It will likely be the middle of the week after next before I can review it.

**Comment by carl-wallace** [comment]
Completed by merge #62.
