### ISSUE TITLE
Ensure SignatureAlgorithm equality in path validation

### ISSUE THREAD

**Issue by OliverUv** [carl-wallace/rust-pki#7]
Hope it's alright to add TODOs in the issue tracker. If not, please notify me.

`Certificate::signatureAlgorithm` must be equal to `Certificate::tbsCertificate::signature`. I.e. for each x509 certificate, its two instances of `AlgorithmIdentifier` must be equal.

This is a check that needs to be done bit wise because there are multiple ways of specifying the same algorithm (e.g. multiple OIDs signifying the same algorithm).

Attacks on systems that fail to perform this check seem **very** theoretical, but it doesn't hurt to do the check.

Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1077864

Additional context: https://security.stackexchange.com/questions/114746/why-is-the-signature-algorithm-listed-twice-in-an-x509-certificate/115334#115334

**Comment by carl-wallace** [comment]
Issues are fine. I will likely spend sometime in a few weeks on addressing places that are carrying references that don't need to now that formats uses owned types. The check in this issue can just be added to the validator. I'll add that next time working on the library.

**Comment by carl-wallace** [comment]
Added a check before signature validation in #18
